services:
  - type: web
    name: category-recommender-api
    runtime: python
    buildCommand: ""
    startCommand: uvicorn main:app --reload
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
